"""Public GUI backend boundary; no optimizer implementation is imported here."""

from .contracts import (
    BackendAvailability,
    BackendError,
    BatchOptimizationCancelled,
    BatchOptimizationResult,
    CancellationToken,
    GuiBatchOptimizationRequest,
    GuiOptimizationResult,
    HeatmapMessageDetail,
    HeatmapSlotDetail,
    HeatmapWindowDetail,
    ImportSession,
    LoadWindowMetadata,
    NetworkBatchResult,
    NetworkSummary,
    OptimizationBackend,
    OptimizationCancelled,
    ProgressCallback,
    ProgressUpdate,
    SenderNodeSelectionConfig,
    WorkspaceInspection,
)

__all__ = [
    "BackendAvailability",
    "BackendError",
    "BatchOptimizationCancelled",
    "BatchOptimizationResult",
    "CancellationToken",
    "GuiBatchOptimizationRequest",
    "GuiOptimizationResult",
    "HeatmapMessageDetail",
    "HeatmapSlotDetail",
    "HeatmapWindowDetail",
    "ImportSession",
    "LoadWindowMetadata",
    "NetworkBatchResult",
    "NetworkSummary",
    "OptimizationBackend",
    "OptimizationCancelled",
    "ProgressCallback",
    "ProgressUpdate",
    "SenderNodeSelectionConfig",
    "WorkspaceInspection",
]
